site_name:        UncertainData.jl
repo_url:         https://github.com/kahaaga/UncertainData.jl
site_description: Datasets and values with associated uncertainties.
site_author:      Kristian Agasøster Haaga

theme: material

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
      baselevel: 1
      separator: "_"

docs_dir: 'build'

pages:
  - Home: index.md
  - Uncertain values:
    - Quickstart: uncertainvalues_overview.md
    - Kernel density estimates (KDE): uncertainvalues_kde.md
    - Theoretical distributions: uncertainvalues_theoreticaldistributions.md
    - Fit theoretical distributions: uncertainvalues_fitted.md
  - Uncertain statistics:
    - Core statistics: ensemble_statistics.md
    - Hypothesis tests:
      - Overview: hypothesistests/hypothesis_tests_overview.md
      - One sample t-test: hypothesistests/one_sample_t_test.md
      - Equal variance t-test: hypothesistests/equal_variance_t_test.md
      - Unequal variance t-test: hypothesistests/unequal_variance_t_test.md
      - Exact Kolmogorov-Smirnov test: hypothesistests/exact_kolmogorov_smirnov_test.md
      - Approximate two-sample Kolmogorov-Smirnov test: hypothesistests/approximate_twosample_kolmogorov_smirnov_test.md
      - Jarque-Bera test: hypothesistests/jarque_bera_test.md
      - Mann-Whitney u-test: hypothesistests/mann_whitney_u_test.md
      - Anderson-Darling test: hypothesistests/anderson_darling_test.md
  - Resampling: resampling.md
  - Implementing algorithms for uncertain data: implementing_algorithms_for_uncertaindata.md
